{{- if .Values.autoScale.enabled  }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dateTrivia.fullname" . }}-backend
  labels:
{{ include "dateTrivia.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dateTrivia.fullname" . }}-backend
  minReplicas: {{  .Values.autoScale.backend.minReplicas  }}
  maxReplicas: {{  .Values.autoScale.backend.maxReplicas  }}
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dateTrivia.fullname" . }}-frontend
  labels:
{{ include "dateTrivia.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dateTrivia.fullname" . }}-frontend
  minReplicas: {{  .Values.autoScale.backend.minReplicas  }}
  maxReplicas: {{  .Values.autoScale.backend.maxReplicas  }}
  targetCPUUtilizationPercentage: 80
{{- end  }}