apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dateTrivia.name" . }}-backend-config
  labels:
    app: {{ include "dateTrivia.fullname" . }}-backend
    chart: {{  template "dateTrivia.chart" .  }}
    release: {{  .Release.Service  }}
data:
  DEBUG: "FALSE"
  HOST: "0.0.0.0"
  PORT: "{{  .Values.backend.ports.internalPort  }}"
  TZ: "{{  .Values.timezone  }}"