apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dateTrivia.name" . }}-frontend-config
  labels:
    app: {{ include "dateTrivia.fullname" . }}-frontend
    chart: {{  template "dateTrivia.chart" .  }}
    release: {{  .Release.Service  }}
data:
  DEBUG: "FALSE"
  HOST: "0.0.0.0"
  PORT: "{{  .Values.frontend.ports.internalPort  }}"
  TRIVIA_ADDRESS: "http://{{ include "dateTrivia.fullname" . }}-backend.{{  .Release.Namespace  }}.svc.{{  .Values.cluster_name  }}"