{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dateTrivia.serviceAccountName" . }}
  labels:
{{ include "dateTrivia.labels" . | indent 4 }}
{{- end -}}
