apiVersion: v1
kind: Service
metadata:
  name: {{ include "dateTrivia.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "dateTrivia.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}-frontend
spec:
  type: {{ .Values.service.frontend.type  }}
  ports:
    - port: {{  .Values.service.frontend.port  }}
      targetPort: {{  .Values.service.frontend.targetPort  }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "dateTrivia.name" . }}-frontend
    app.kubernetes.io/instance: {{  .Release.Name  }}-frontend
